// ═══════════════════════════════════════════════════════════════════════════════
// AscendifyIFY - Template Library Data
// Pre-built habit and goal templates for quick start
// ═══════════════════════════════════════════════════════════════════════════════

import { HabitTemplate, GoalTemplate, TemplateBundle, TemplateCategory } from '@/types';

// ─────────────────────────────────────────────────────────────────────────────────
// HABIT TEMPLATES (25+ covering all categories)
// ─────────────────────────────────────────────────────────────────────────────────

export const HABIT_TEMPLATES: HabitTemplate[] = [
  // ═══════════════════════════════════════════════════════════════════════════════
  // HEALTH & FITNESS (8 templates)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'h-exercise-morning',
    name: 'Morning Exercise',
    description: 'Start your day with 30 minutes of exercise to boost energy and mood',
    category: 'fitness',
    frequency: 'daily',
    icon: '💪',
    color: '#10B981',
    xpReward: 25,
    duration: 30,
    difficulty: 'medium',
    scientificBasis: 'Morning exercise increases cortisol naturally, improving alertness and reducing stress hormones throughout the day.',
    tips: ['Start with just 10 minutes if 30 feels overwhelming', 'Lay out your workout clothes the night before', 'Try a mix of cardio and strength training'],
    tags: ['morning-routine', 'energy', 'fitness'],
    popular: true,
    isBuiltIn: true,
  },
  {
    id: 'h-water-intake',
    name: 'Drink 8 Glasses of Water',
    description: 'Stay hydrated throughout the day with adequate water intake',
    category: 'health',
    frequency: 'daily',
    icon: '💧',
    color: '#3B82F6',
    xpReward: 15,
    targetCompletions: 8,
    difficulty: 'easy',
    scientificBasis: 'Proper hydration improves cognitive function, energy levels, and helps maintain healthy skin and digestion.',
    tips: ['Keep a water bottle at your desk', 'Drink a glass before each meal', 'Set hourly reminders'],
    tags: ['hydration', 'health', 'easy-win'],
    popular: true,
    isBuiltIn: true,
  },
  {
    id: 'h-10k-steps',
    name: '10,000 Steps',
    description: 'Walk at least 10,000 steps daily for cardiovascular health',
    category: 'fitness',
    frequency: 'daily',
    icon: '🚶',
    color: '#10B981',
    xpReward: 20,
    difficulty: 'medium',
    scientificBasis: 'Walking 10,000 steps burns approximately 400-500 calories and significantly reduces risk of cardiovascular disease.',
    tips: ['Take the stairs instead of the elevator', 'Park farther away from entrances', 'Have walking meetings'],
    tags: ['walking', 'cardio', 'daily-movement'],
    popular: true,
    isBuiltIn: true,
  },
  {
    id: 'h-no-junk-food',
    name: 'No Junk Food',
    description: 'Avoid processed and junk food for better health',
    category: 'nutrition',
    frequency: 'daily',
    icon: '🥗',
    color: '#22C55E',
    xpReward: 20,
    difficulty: 'hard',
    scientificBasis: 'Reducing processed food intake lowers inflammation, improves gut health, and stabilizes energy levels.',
    tips: ['Meal prep healthy snacks', 'Keep junk food out of the house', 'Find healthy alternatives you enjoy'],
    tags: ['nutrition', 'clean-eating', 'health'],
    isBuiltIn: true,
  },
  {
    id: 'h-stretching',
    name: 'Daily Stretching',
    description: '10 minutes of stretching to improve flexibility and reduce tension',
    category: 'health',
    frequency: 'daily',
    icon: '🧘',
    color: '#8B5CF6',
    xpReward: 15,
    duration: 10,
    difficulty: 'easy',
    scientificBasis: 'Regular stretching improves range of motion, reduces injury risk, and alleviates muscle tension from sitting.',
    tips: ['Stretch right after waking up', 'Focus on areas that feel tight', 'Never stretch to the point of pain'],
    tags: ['flexibility', 'mobility', 'morning-routine'],
    isBuiltIn: true,
  },
  {
    id: 'h-strength-training',
    name: 'Strength Training',
    description: '45-minute strength workout to build muscle and boost metabolism',
    category: 'fitness',
    frequency: 'custom',
    targetDays: [1, 3, 5], // Mon, Wed, Fri
    icon: '🏋️',
    color: '#EF4444',
    xpReward: 35,
    duration: 45,
    difficulty: 'hard',
    scientificBasis: 'Resistance training increases muscle mass, improves bone density, and boosts resting metabolic rate.',
    tips: ['Focus on compound movements', 'Progressive overload is key', 'Allow adequate rest between sessions'],
    tags: ['strength', 'muscle', 'fitness'],
    isBuiltIn: true,
  },
  {
    id: 'h-protein-intake',
    name: 'Hit Protein Goal',
    description: 'Consume adequate protein (0.8-1g per lb bodyweight) daily',
    category: 'nutrition',
    frequency: 'daily',
    icon: '🥩',
    color: '#DC2626',
    xpReward: 15,
    difficulty: 'medium',
    scientificBasis: 'Adequate protein intake supports muscle recovery, satiety, and healthy body composition.',
    tips: ['Include protein in every meal', 'Track your intake for a week to establish baseline', 'Consider protein supplements if needed'],
    tags: ['nutrition', 'protein', 'fitness'],
    isBuiltIn: true,
  },
  {
    id: 'h-cold-shower',
    name: 'Cold Shower',
    description: 'End your shower with 30-60 seconds of cold water',
    category: 'health',
    frequency: 'daily',
    icon: '🚿',
    color: '#06B6D4',
    xpReward: 20,
    difficulty: 'hard',
    scientificBasis: 'Cold exposure increases alertness, improves circulation, and may boost immune function.',
    tips: ['Start with just 10 seconds', 'Breathe slowly and deeply', 'End on cold, not warm'],
    tags: ['cold-exposure', 'discipline', 'energy'],
    isBuiltIn: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // PRODUCTIVITY (6 templates)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'h-deep-work',
    name: 'Deep Work Session',
    description: '2 hours of focused, uninterrupted work on your most important task',
    category: 'productivity',
    frequency: 'daily',
    icon: '🎯',
    color: '#F59E0B',
    xpReward: 30,
    duration: 120,
    difficulty: 'hard',
    scientificBasis: 'Cal Newport\'s research shows that deep work produces higher quality output and is becoming increasingly rare and valuable.',
    tips: ['Block your calendar', 'Turn off all notifications', 'Work on your #1 priority first'],
    tags: ['focus', 'productivity', 'deep-work'],
    popular: true,
    isBuiltIn: true,
  },
  {
    id: 'h-plan-tomorrow',
    name: 'Plan Tomorrow',
    description: 'Spend 10 minutes planning and prioritizing tomorrow\'s tasks',
    category: 'productivity',
    frequency: 'daily',
    icon: '📋',
    color: '#6366F1',
    xpReward: 15,
    duration: 10,
    difficulty: 'easy',
    scientificBasis: 'Planning the night before reduces decision fatigue and allows your subconscious to work on problems overnight.',
    tips: ['List your top 3 priorities', 'Block time for deep work', 'Identify potential obstacles'],
    tags: ['planning', 'evening-routine', 'productivity'],
    popular: true,
    isBuiltIn: true,
  },
  {
    id: 'h-inbox-zero',
    name: 'Inbox Zero',
    description: 'Process all emails to zero at least once daily',
    category: 'productivity',
    frequency: 'daily',
    icon: '📧',
    color: '#EC4899',
    xpReward: 20,
    difficulty: 'medium',
    scientificBasis: 'Regular inbox processing prevents email overwhelm and ensures nothing important falls through the cracks.',
    tips: ['Set specific times to check email', 'Use the 2-minute rule', 'Unsubscribe ruthlessly'],
    tags: ['email', 'organization', 'productivity'],
    isBuiltIn: true,
  },
  {
    id: 'h-no-social-media-morning',
    name: 'No Social Media Before Noon',
    description: 'Protect your morning focus by avoiding social media until afternoon',
    category: 'productivity',
    frequency: 'daily',
    icon: '📵',
    color: '#EF4444',
    xpReward: 25,
    difficulty: 'hard',
    scientificBasis: 'Morning social media use trains your brain for distraction and depletes willpower for the day.',
    tips: ['Remove apps from your phone', 'Use website blockers', 'Replace with a positive habit'],
    tags: ['digital-wellness', 'focus', 'morning-routine'],
    isBuiltIn: true,
  },
  {
    id: 'h-pomodoro-sessions',
    name: 'Complete 4 Pomodoros',
    description: 'Complete four 25-minute focused work sessions with breaks',
    category: 'productivity',
    frequency: 'daily',
    icon: '🍅',
    color: '#EF4444',
    xpReward: 25,
    targetCompletions: 4,
    difficulty: 'medium',
    scientificBasis: 'The Pomodoro Technique uses time boxing to maintain focus and prevent burnout.',
    tips: ['Start with your most important task', 'Take real breaks away from screen', 'Track your daily pomodoro count'],
    tags: ['pomodoro', 'focus', 'time-management'],
    isBuiltIn: true,
  },
  {
    id: 'h-weekly-review',
    name: 'Weekly Review',
    description: 'Review your week: wins, lessons, and plan for next week',
    category: 'productivity',
    frequency: 'weekly',
    targetDays: [0], // Sunday
    icon: '📊',
    color: '#8B5CF6',
    xpReward: 40,
    duration: 30,
    difficulty: 'medium',
    scientificBasis: 'Regular reflection improves self-awareness and helps identify patterns for continuous improvement.',
    tips: ['Block 30 minutes every Sunday', 'Celebrate wins, no matter how small', 'Adjust your systems based on what worked'],
    tags: ['review', 'reflection', 'planning'],
    isBuiltIn: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // LEARNING (5 templates)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'h-reading',
    name: 'Read for 30 Minutes',
    description: 'Daily reading habit to expand knowledge and perspective',
    category: 'learning',
    frequency: 'daily',
    icon: '📚',
    color: '#8B5CF6',
    xpReward: 20,
    duration: 30,
    difficulty: 'easy',
    scientificBasis: 'Reading 30 minutes daily can result in 20+ books per year and significantly improves vocabulary and cognitive function.',
    tips: ['Read first thing in the morning or before bed', 'Keep a book with you always', 'Alternate between fiction and non-fiction'],
    tags: ['reading', 'learning', 'self-improvement'],
    popular: true,
    isBuiltIn: true,
  },
  {
    id: 'h-learn-vocabulary',
    name: 'Learn a New Word',
    description: 'Expand your vocabulary with one new word daily',
    category: 'learning',
    frequency: 'daily',
    icon: '📖',
    color: '#06B6D4',
    xpReward: 10,
    difficulty: 'easy',
    scientificBasis: 'A rich vocabulary improves communication, reading comprehension, and cognitive processing.',
    tips: ['Use word-a-day apps or calendars', 'Try to use the new word in conversation', 'Review previous words weekly'],
    tags: ['vocabulary', 'language', 'learning'],
    isBuiltIn: true,
  },
  {
    id: 'h-language-practice',
    name: 'Practice a Language',
    description: '15 minutes of language learning with apps or conversation',
    category: 'learning',
    frequency: 'daily',
    icon: '🌍',
    color: '#14B8A6',
    xpReward: 20,
    duration: 15,
    difficulty: 'medium',
    scientificBasis: 'Daily language practice, even briefly, creates stronger neural pathways than longer infrequent sessions.',
    tips: ['Use apps like Duolingo or Babbel', 'Practice speaking out loud', 'Consume media in your target language'],
    tags: ['language', 'skills', 'learning'],
    popular: true,
    isBuiltIn: true,
  },
  {
    id: 'h-online-course',
    name: 'Online Course Progress',
    description: 'Complete one lesson or module from an online course',
    category: 'learning',
    frequency: 'daily',
    icon: '🎓',
    color: '#F43F5E',
    xpReward: 25,
    duration: 20,
    difficulty: 'medium',
    scientificBasis: 'Consistent small progress on learning goals leads to skill acquisition through spaced repetition.',
    tips: ['Set a specific course and deadline', 'Take notes while learning', 'Apply what you learn immediately'],
    tags: ['education', 'skills', 'learning'],
    isBuiltIn: true,
  },
  {
    id: 'h-teach-something',
    name: 'Teach Something',
    description: 'Explain a concept you learned to someone else or write about it',
    category: 'learning',
    frequency: 'weekly',
    targetDays: [5], // Friday
    icon: '👨‍🏫',
    color: '#F59E0B',
    xpReward: 30,
    difficulty: 'medium',
    scientificBasis: 'The Feynman Technique: teaching forces you to truly understand a concept and reveals gaps in knowledge.',
    tips: ['Write a blog post or social media thread', 'Explain to a friend or family member', 'Record a video for yourself'],
    tags: ['teaching', 'knowledge', 'learning'],
    isBuiltIn: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // MINDFULNESS & MENTAL HEALTH (5 templates)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'h-meditation',
    name: 'Morning Meditation',
    description: '10 minutes of mindfulness meditation to start the day centered',
    category: 'mindfulness',
    frequency: 'daily',
    icon: '🧘',
    color: '#8B5CF6',
    xpReward: 20,
    duration: 10,
    difficulty: 'medium',
    scientificBasis: 'Regular meditation reduces cortisol, increases gray matter in the brain, and improves emotional regulation.',
    tips: ['Start with guided meditations', 'Same time, same place each day', 'Don\'t judge your practice'],
    tags: ['meditation', 'morning-routine', 'mental-health'],
    popular: true,
    isBuiltIn: true,
  },
  {
    id: 'h-gratitude-journal',
    name: 'Gratitude Journal',
    description: 'Write 3 things you\'re grateful for each day',
    category: 'mindfulness',
    frequency: 'daily',
    icon: '🙏',
    color: '#F59E0B',
    xpReward: 15,
    duration: 5,
    difficulty: 'easy',
    scientificBasis: 'Gratitude journaling is linked to increased happiness, better sleep, and reduced depression symptoms.',
    tips: ['Be specific, not generic', 'Include at least one person', 'Do it at the same time daily'],
    tags: ['gratitude', 'journaling', 'happiness'],
    popular: true,
    isBuiltIn: true,
  },
  {
    id: 'h-digital-detox',
    name: 'Digital Detox Hour',
    description: 'One hour without any screens - read, walk, or connect with others',
    category: 'mindfulness',
    frequency: 'daily',
    icon: '🌿',
    color: '#22C55E',
    xpReward: 20,
    duration: 60,
    difficulty: 'hard',
    scientificBasis: 'Screen breaks reduce eye strain, improve sleep quality, and allow for deeper in-person connections.',
    tips: ['Schedule it like an appointment', 'Have alternative activities ready', 'Tell others you\'re offline'],
    tags: ['digital-wellness', 'presence', 'mental-health'],
    isBuiltIn: true,
  },
  {
    id: 'h-evening-reflection',
    name: 'Evening Reflection',
    description: 'Reflect on your day: wins, lessons, and tomorrow\'s intentions',
    category: 'mindfulness',
    frequency: 'daily',
    icon: '🌙',
    color: '#6366F1',
    xpReward: 15,
    duration: 5,
    difficulty: 'easy',
    scientificBasis: 'Evening reflection improves self-awareness and helps process the day\'s experiences.',
    tips: ['Ask: What went well? What could be better?', 'Write it down', 'Keep it brief - 5 minutes max'],
    tags: ['reflection', 'evening-routine', 'mindfulness'],
    isBuiltIn: true,
  },
  {
    id: 'h-nature-time',
    name: 'Time in Nature',
    description: 'Spend 20 minutes outdoors in nature',
    category: 'mindfulness',
    frequency: 'daily',
    icon: '🌳',
    color: '#22C55E',
    xpReward: 20,
    duration: 20,
    difficulty: 'easy',
    scientificBasis: 'Time in nature reduces cortisol, lowers blood pressure, and improves mood and cognitive function.',
    tips: ['A park counts as nature', 'Leave your phone behind', 'Try to notice 5 things you see, hear, smell'],
    tags: ['nature', 'outdoor', 'mental-health'],
    isBuiltIn: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // SLEEP (3 templates)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'h-sleep-early',
    name: 'Sleep by 10 PM',
    description: 'Get to bed by 10 PM for optimal recovery and energy',
    category: 'sleep',
    frequency: 'daily',
    icon: '😴',
    color: '#6366F1',
    xpReward: 25,
    difficulty: 'hard',
    scientificBasis: 'Sleep before midnight is more restorative due to alignment with natural circadian rhythms.',
    tips: ['Set an alarm at 9 PM to start winding down', 'Dim lights 2 hours before bed', 'No caffeine after 2 PM'],
    tags: ['sleep', 'evening-routine', 'recovery'],
    isBuiltIn: true,
  },
  {
    id: 'h-no-screens-bed',
    name: 'No Screens Before Bed',
    description: 'Avoid screens 1 hour before sleep',
    category: 'sleep',
    frequency: 'daily',
    icon: '📵',
    color: '#8B5CF6',
    xpReward: 20,
    difficulty: 'hard',
    scientificBasis: 'Blue light from screens suppresses melatonin production, making it harder to fall asleep.',
    tips: ['Read a physical book instead', 'Use night mode if you must use devices', 'Charge your phone outside the bedroom'],
    tags: ['sleep', 'digital-wellness', 'evening-routine'],
    isBuiltIn: true,
  },
  {
    id: 'h-sleep-routine',
    name: 'Bedtime Routine',
    description: 'Follow a consistent 20-minute wind-down routine before bed',
    category: 'sleep',
    frequency: 'daily',
    icon: '🌙',
    color: '#7C3AED',
    xpReward: 15,
    duration: 20,
    difficulty: 'medium',
    scientificBasis: 'A consistent bedtime routine signals to your brain that it\'s time to sleep, improving sleep onset.',
    tips: ['Include: brush teeth, skincare, light stretching, reading', 'Same order every night', 'Keep it calming, not stimulating'],
    tags: ['sleep', 'routine', 'evening-routine'],
    isBuiltIn: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // SOCIAL & RELATIONSHIPS (3 templates)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'h-connect-friend',
    name: 'Connect with a Friend',
    description: 'Reach out to a friend or family member daily',
    category: 'social',
    frequency: 'daily',
    icon: '👋',
    color: '#EC4899',
    xpReward: 15,
    difficulty: 'easy',
    scientificBasis: 'Social connection is one of the strongest predictors of happiness and longevity.',
    tips: ['Send a quick text or voice message', 'Share something that made you think of them', 'Schedule recurring calls with close friends'],
    tags: ['relationships', 'social', 'happiness'],
    isBuiltIn: true,
  },
  {
    id: 'h-family-time',
    name: 'Quality Family Time',
    description: 'Spend 30 minutes of undivided attention with family',
    category: 'relationships',
    frequency: 'daily',
    icon: '👨‍👩‍👧‍👦',
    color: '#F43F5E',
    xpReward: 20,
    duration: 30,
    difficulty: 'medium',
    scientificBasis: 'Quality time strengthens family bonds and provides emotional security for all family members.',
    tips: ['Put phones away', 'Do an activity together', 'Have device-free meals'],
    tags: ['family', 'relationships', 'presence'],
    isBuiltIn: true,
  },
  {
    id: 'h-act-of-kindness',
    name: 'Random Act of Kindness',
    description: 'Do one unexpected kind thing for someone else',
    category: 'social',
    frequency: 'daily',
    icon: '💝',
    color: '#EC4899',
    xpReward: 15,
    difficulty: 'easy',
    scientificBasis: 'Acts of kindness boost both the giver\'s and receiver\'s wellbeing and create positive ripple effects.',
    tips: ['Hold a door, compliment someone, pay for someone\'s coffee', 'Small gestures count', 'Look for opportunities throughout the day'],
    tags: ['kindness', 'social', 'happiness'],
    isBuiltIn: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // FINANCE (2 templates)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'h-track-expenses',
    name: 'Track Expenses',
    description: 'Log all your spending for the day',
    category: 'finance',
    frequency: 'daily',
    icon: '💰',
    color: '#22C55E',
    xpReward: 15,
    difficulty: 'easy',
    scientificBasis: 'Awareness of spending patterns is the first step to financial improvement and reduces impulse purchases.',
    tips: ['Use an app to make it easy', 'Do it right after each purchase', 'Categorize your expenses'],
    tags: ['money', 'tracking', 'finance'],
    isBuiltIn: true,
  },
  {
    id: 'h-no-impulse-buying',
    name: 'No Impulse Purchases',
    description: 'Wait 24-48 hours before any non-essential purchase over $20',
    category: 'finance',
    frequency: 'daily',
    icon: '🛒',
    color: '#F59E0B',
    xpReward: 20,
    difficulty: 'hard',
    scientificBasis: 'Delaying purchases reduces impulse buying by up to 90% and leads to more intentional spending.',
    tips: ['Add items to a wishlist instead of cart', 'Ask: Do I need this or want this?', 'Sleep on big purchases'],
    tags: ['money', 'discipline', 'finance'],
    isBuiltIn: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // CREATIVE (3 templates)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'h-creative-practice',
    name: 'Creative Practice',
    description: '30 minutes of creative work: art, music, writing, or craft',
    category: 'creative',
    frequency: 'daily',
    icon: '🎨',
    color: '#EC4899',
    xpReward: 25,
    duration: 30,
    difficulty: 'medium',
    scientificBasis: 'Regular creative practice improves problem-solving, reduces stress, and enhances overall cognitive function.',
    tips: ['Don\'t judge the output, focus on the process', 'Same time each day builds the habit', 'Keep supplies accessible'],
    tags: ['creativity', 'art', 'self-expression'],
    isBuiltIn: true,
  },
  {
    id: 'h-write-500-words',
    name: 'Write 500 Words',
    description: 'Daily writing practice - journal, blog, fiction, or work',
    category: 'creative',
    frequency: 'daily',
    icon: '✍️',
    color: '#6366F1',
    xpReward: 25,
    difficulty: 'medium',
    scientificBasis: 'Daily writing improves clarity of thought, communication skills, and can lead to creative breakthroughs.',
    tips: ['Morning pages work great', 'Don\'t edit while writing', 'Quantity over quality for daily practice'],
    tags: ['writing', 'creativity', 'self-expression'],
    popular: true,
    isBuiltIn: true,
  },
  {
    id: 'h-play-music',
    name: 'Practice an Instrument',
    description: '20 minutes of focused music practice',
    category: 'creative',
    frequency: 'daily',
    icon: '🎸',
    color: '#8B5CF6',
    xpReward: 20,
    duration: 20,
    difficulty: 'medium',
    scientificBasis: 'Music practice enhances memory, coordination, and mathematical abilities while reducing stress.',
    tips: ['Consistent short sessions beat occasional long ones', 'Practice slowly before speeding up', 'Record yourself to track progress'],
    tags: ['music', 'creativity', 'skills'],
    isBuiltIn: true,
  },
];

// ─────────────────────────────────────────────────────────────────────────────────
// GOAL TEMPLATES (15+ covering all categories)
// ─────────────────────────────────────────────────────────────────────────────────

export const GOAL_TEMPLATES: GoalTemplate[] = [
  // ═══════════════════════════════════════════════════════════════════════════════
  // FITNESS GOALS (4 templates)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'g-run-marathon',
    title: 'Run a Marathon',
    description: 'Train and complete a full 42.2km (26.2 mile) marathon',
    category: 'fitness',
    icon: '🏃',
    timeframe: '6 months',
    timeframeDays: 180,
    suggestedHabits: ['h-exercise-morning', 'h-10k-steps', 'h-water-intake', 'h-stretching'],
    suggestedMilestones: [
      { title: 'Foundation Phase', description: 'Build base fitness with 3-4 runs per week', weekNumber: 4, objectives: ['Run 5K comfortably', 'Establish running schedule', 'Get proper running shoes'] },
      { title: 'Endurance Building', description: 'Increase weekly mileage gradually', weekNumber: 10, objectives: ['Complete 10K run', 'Average 20 miles per week', 'Master running nutrition'] },
      { title: 'Half Marathon Ready', description: 'Complete half marathon distance', weekNumber: 16, objectives: ['Run 13.1 miles', 'Refine race pace', 'Practice race day routine'] },
      { title: 'Peak Training', description: 'Peak mileage weeks', weekNumber: 22, objectives: ['Complete 20-mile run', 'Maintain consistent pace', 'Mental preparation'] },
      { title: 'Taper & Race', description: 'Rest and race!', weekNumber: 24, objectives: ['Reduce mileage 40%', 'Carb load properly', 'Complete marathon!'] },
    ],
    targetOutcome: 'Cross the marathon finish line and earn that medal',
    successMetrics: ['Complete marathon under 5 hours', 'No injuries during training', 'Enjoy the process'],
    difficulty: 'expert',
    tags: ['running', 'endurance', 'fitness'],
    popular: true,
    isBuiltIn: true,
  },
  {
    id: 'g-run-5k',
    title: 'Run Your First 5K',
    description: 'Go from couch to completing a 5K (3.1 miles) run',
    category: 'fitness',
    icon: '🏃‍♀️',
    timeframe: '8 weeks',
    timeframeDays: 56,
    suggestedHabits: ['h-exercise-morning', 'h-stretching', 'h-water-intake'],
    suggestedMilestones: [
      { title: 'Walk-Run Foundation', description: 'Alternate walking and jogging', weekNumber: 2, objectives: ['Walk/run 20 minutes', 'Run for 1-2 minutes at a time', 'Establish 3x per week routine'] },
      { title: 'Build Running Time', description: 'Increase running intervals', weekNumber: 4, objectives: ['Run 5 minutes continuously', 'Cover 1.5 miles total', 'Focus on breathing'] },
      { title: 'Run Continuous', description: 'Run without walking breaks', weekNumber: 6, objectives: ['Run 2 miles non-stop', 'Establish comfortable pace', 'Add 4th running day'] },
      { title: 'Race Ready', description: 'Complete your 5K!', weekNumber: 8, objectives: ['Run full 3.1 miles', 'Sign up for a race', 'Celebrate your achievement!'] },
    ],
    targetOutcome: 'Complete a 5K run without stopping',
    successMetrics: ['Run 5K continuously', 'Finish in under 40 minutes', 'Feel proud of accomplishment'],
    difficulty: 'easy',
    tags: ['running', 'beginner', 'fitness'],
    popular: true,
    isBuiltIn: true,
  },
  {
    id: 'g-lose-weight',
    title: 'Lose 20 Pounds Sustainably',
    description: 'Reach a healthy weight through sustainable habits, not crash dieting',
    category: 'health',
    icon: '⚖️',
    timeframe: '5 months',
    timeframeDays: 150,
    suggestedHabits: ['h-exercise-morning', 'h-no-junk-food', 'h-water-intake', 'h-protein-intake'],
    suggestedMilestones: [
      { title: 'Foundation', description: 'Establish tracking and basic habits', weekNumber: 2, objectives: ['Track all food intake', 'Establish exercise routine', 'Remove junk food from house'] },
      { title: 'First 5 Pounds', description: 'Initial weight loss phase', weekNumber: 6, objectives: ['Lose 5 pounds', 'Find healthy meals you enjoy', 'Handle one social event successfully'] },
      { title: 'Halfway There', description: '10 pounds down, 10 to go', weekNumber: 12, objectives: ['Reach -10 pounds', 'Increase workout intensity', 'Non-scale victories: clothes fit better'] },
      { title: 'Final Push', description: 'Last 10 pounds', weekNumber: 18, objectives: ['Lose remaining weight', 'Build maintenance habits', 'Plan for long-term success'] },
      { title: 'Maintenance', description: 'Lock in your new lifestyle', weekNumber: 20, objectives: ['Maintain weight for 2 weeks', 'Establish maintenance calories', 'Celebrate transformation!'] },
    ],
    targetOutcome: 'Lose 20 pounds and maintain a healthy lifestyle',
    successMetrics: ['Lose 20 pounds', 'Keep it off for 3+ months', 'Improved energy and confidence'],
    difficulty: 'hard',
    tags: ['weight-loss', 'health', 'nutrition'],
    popular: true,
    isBuiltIn: true,
  },
  {
    id: 'g-build-muscle',
    title: 'Build Noticeable Muscle',
    description: 'Gain 10 pounds of lean muscle through strength training and nutrition',
    category: 'fitness',
    icon: '💪',
    timeframe: '6 months',
    timeframeDays: 180,
    suggestedHabits: ['h-strength-training', 'h-protein-intake', 'h-water-intake', 'h-sleep-early'],
    targetOutcome: 'Gain 10 pounds of muscle and significantly increase strength',
    successMetrics: ['Gain 10 lbs of lean mass', 'Double strength on main lifts', 'Visible muscle definition'],
    difficulty: 'hard',
    tags: ['muscle', 'strength', 'fitness'],
    isBuiltIn: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // LEARNING GOALS (4 templates)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'g-read-50-books',
    title: 'Read 50 Books This Year',
    description: 'Develop a consistent reading habit and complete 50 books',
    category: 'learning',
    icon: '📚',
    timeframe: '12 months',
    timeframeDays: 365,
    suggestedHabits: ['h-reading', 'h-digital-detox'],
    suggestedMilestones: [
      { title: 'Reading Habit', description: 'Establish daily reading routine', weekNumber: 4, objectives: ['Read 4 books', 'Find best time to read', 'Create reading list'] },
      { title: 'Quarter One', description: '12 books down', weekNumber: 13, objectives: ['Complete 12 books', 'Mix fiction and non-fiction', 'Join a book club or community'] },
      { title: 'Halfway Point', description: '25 books complete', weekNumber: 26, objectives: ['Finish book 25', 'Try a new genre', 'Share recommendations'] },
      { title: 'The Home Stretch', description: '37 books down', weekNumber: 39, objectives: ['Complete 37 books', 'Write mini reviews', 'Identify favorite authors'] },
      { title: 'Mission Complete', description: '50 books!', weekNumber: 52, objectives: ['Finish book 50!', 'Compile year-end list', 'Share your reading journey'] },
    ],
    targetOutcome: 'Read 50 diverse books and expand your knowledge',
    successMetrics: ['Complete 50 books', 'Read across 5+ genres', 'Retain and apply key insights'],
    difficulty: 'medium',
    tags: ['reading', 'learning', 'self-improvement'],
    popular: true,
    isBuiltIn: true,
  },
  {
    id: 'g-learn-language',
    title: 'Learn a New Language',
    description: 'Achieve conversational fluency in a new language',
    category: 'learning',
    icon: '🌍',
    timeframe: '12 months',
    timeframeDays: 365,
    suggestedHabits: ['h-language-practice', 'h-learn-vocabulary'],
    suggestedMilestones: [
      { title: 'Foundation', description: 'Learn basics and build habit', weekNumber: 8, objectives: ['Master 500 words', 'Basic grammar', 'Daily practice streak'] },
      { title: 'Conversational Basics', description: 'Hold simple conversations', weekNumber: 20, objectives: ['1500 word vocabulary', 'Simple conversations', 'Watch content with subtitles'] },
      { title: 'Intermediate', description: 'Understand and be understood', weekNumber: 35, objectives: ['3000 word vocabulary', 'Read simple books', 'Talk with native speakers'] },
      { title: 'Fluent', description: 'Conversational fluency', weekNumber: 52, objectives: ['Fluent conversations', 'Think in the language', 'Watch content without subtitles'] },
    ],
    targetOutcome: 'Have a full conversation with a native speaker',
    successMetrics: ['30-minute conversation', 'Understand 90% of spoken content', 'Read a book in target language'],
    difficulty: 'hard',
    tags: ['language', 'learning', 'skills'],
    popular: true,
    isBuiltIn: true,
  },
  {
    id: 'g-learn-coding',
    title: 'Learn to Code',
    description: 'Go from zero to building your own web applications',
    category: 'learning',
    icon: '💻',
    timeframe: '6 months',
    timeframeDays: 180,
    suggestedHabits: ['h-online-course', 'h-deep-work', 'h-pomodoro-sessions'],
    suggestedMilestones: [
      { title: 'Fundamentals', description: 'Learn programming basics', weekNumber: 4, objectives: ['Complete HTML/CSS basics', 'Write first JavaScript', 'Understand variables, loops, functions'] },
      { title: 'Build Projects', description: 'Create mini projects', weekNumber: 10, objectives: ['Build 3 mini projects', 'Learn Git basics', 'Join coding community'] },
      { title: 'Framework', description: 'Learn a modern framework', weekNumber: 18, objectives: ['Learn React or Vue', 'Build interactive UI', 'Understand state management'] },
      { title: 'Full Stack', description: 'Build complete applications', weekNumber: 24, objectives: ['Build full-stack app', 'Deploy to production', 'Create portfolio'] },
    ],
    targetOutcome: 'Build and deploy a full web application',
    successMetrics: ['Portfolio with 5+ projects', 'Understand full-stack development', 'Contribute to open source'],
    difficulty: 'hard',
    tags: ['coding', 'tech', 'career'],
    popular: true,
    isBuiltIn: true,
  },
  {
    id: 'g-master-skill',
    title: 'Master a Professional Skill',
    description: 'Become an expert in a specific skill relevant to your career',
    category: 'career',
    icon: '🎯',
    timeframe: '6 months',
    timeframeDays: 180,
    suggestedHabits: ['h-deep-work', 'h-online-course', 'h-teach-something'],
    targetOutcome: 'Be recognized as an expert in your chosen skill',
    successMetrics: ['Complete certification/course', 'Apply skill in real projects', 'Teach others'],
    difficulty: 'hard',
    tags: ['skills', 'career', 'expertise'],
    isBuiltIn: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // CAREER & BUSINESS GOALS (3 templates)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'g-side-business',
    title: 'Build a Side Business',
    description: 'Launch and grow a profitable side project while employed',
    category: 'career',
    icon: '💼',
    timeframe: '6 months',
    timeframeDays: 180,
    suggestedHabits: ['h-deep-work', 'h-plan-tomorrow', 'h-weekly-review'],
    suggestedMilestones: [
      { title: 'Ideation & Validation', description: 'Find and validate your idea', weekNumber: 4, objectives: ['Research 5 business ideas', 'Talk to 10 potential customers', 'Choose one idea to pursue'] },
      { title: 'MVP Build', description: 'Create minimum viable product', weekNumber: 10, objectives: ['Build basic version', 'Get first 5 users', 'Collect feedback'] },
      { title: 'First Revenue', description: 'Make your first sale', weekNumber: 16, objectives: ['Set up payment processing', 'Make first $100', 'Establish pricing'] },
      { title: 'Growth', description: 'Scale to consistent revenue', weekNumber: 24, objectives: ['Reach $1000/month', 'Systematize operations', 'Plan for growth'] },
    ],
    targetOutcome: 'Build a side business generating consistent revenue',
    successMetrics: ['$1000+ monthly revenue', 'Repeatable customer acquisition', 'Positive profit margin'],
    difficulty: 'expert',
    tags: ['business', 'entrepreneurship', 'income'],
    popular: true,
    isBuiltIn: true,
  },
  {
    id: 'g-get-promoted',
    title: 'Get Promoted',
    description: 'Advance to the next level in your career within 12 months',
    category: 'career',
    icon: '📈',
    timeframe: '12 months',
    timeframeDays: 365,
    suggestedHabits: ['h-deep-work', 'h-reading', 'h-plan-tomorrow'],
    suggestedMilestones: [
      { title: 'Assessment', description: 'Understand requirements', weekNumber: 4, objectives: ['Learn promotion criteria', 'Identify skill gaps', 'Find a mentor'] },
      { title: 'Skill Building', description: 'Close skill gaps', weekNumber: 16, objectives: ['Complete key training', 'Take on stretch project', 'Document achievements'] },
      { title: 'Visibility', description: 'Get your work noticed', weekNumber: 32, objectives: ['Present to leadership', 'Build cross-functional relationships', 'Exceed targets by 20%'] },
      { title: 'The Ask', description: 'Make your case', weekNumber: 48, objectives: ['Compile promotion packet', 'Have the conversation', 'Get promoted!'] },
    ],
    targetOutcome: 'Get promoted to the next level',
    successMetrics: ['Receive promotion', 'Salary increase of 15%+', 'Expanded responsibilities'],
    difficulty: 'hard',
    tags: ['career', 'promotion', 'professional'],
    isBuiltIn: true,
  },
  {
    id: 'g-job-change',
    title: 'Land Your Dream Job',
    description: 'Successfully transition to a better role at a great company',
    category: 'career',
    icon: '🎯',
    timeframe: '4 months',
    timeframeDays: 120,
    suggestedHabits: ['h-deep-work', 'h-connect-friend', 'h-online-course'],
    targetOutcome: 'Get hired for your dream job',
    successMetrics: ['Receive job offer', '20%+ salary increase', 'Better work-life balance'],
    difficulty: 'hard',
    tags: ['career', 'job-search', 'professional'],
    isBuiltIn: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // CREATIVE GOALS (2 templates)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'g-write-book',
    title: 'Write a Book',
    description: 'Complete your first novel or non-fiction book (50,000+ words)',
    category: 'creative',
    icon: '✍️',
    timeframe: '12 months',
    timeframeDays: 365,
    suggestedHabits: ['h-write-500-words', 'h-deep-work'],
    suggestedMilestones: [
      { title: 'Planning', description: 'Outline and prepare', weekNumber: 4, objectives: ['Complete detailed outline', 'Establish daily writing routine', 'Set up writing space'] },
      { title: 'First Draft - Act 1', description: 'Write the beginning', weekNumber: 16, objectives: ['Write 15,000 words', 'Establish main characters', 'Hook the reader'] },
      { title: 'First Draft - Act 2', description: 'The middle', weekNumber: 32, objectives: ['Write to 35,000 words', 'Develop plot and subplots', 'Push through the muddle'] },
      { title: 'First Draft - Act 3', description: 'The end', weekNumber: 42, objectives: ['Complete 50,000+ words', 'Write satisfying ending', 'Celebrate finishing!'] },
      { title: 'Revision', description: 'Polish your work', weekNumber: 52, objectives: ['Complete first edit', 'Get beta reader feedback', 'Prepare for publication'] },
    ],
    targetOutcome: 'Complete a polished manuscript ready for publication',
    successMetrics: ['50,000+ words written', 'Complete first draft', 'Get positive beta reader feedback'],
    difficulty: 'expert',
    tags: ['writing', 'creativity', 'book'],
    popular: true,
    isBuiltIn: true,
  },
  {
    id: 'g-learn-instrument',
    title: 'Learn a Musical Instrument',
    description: 'Play songs confidently on a new instrument',
    category: 'creative',
    icon: '🎸',
    timeframe: '6 months',
    timeframeDays: 180,
    suggestedHabits: ['h-play-music', 'h-creative-practice'],
    targetOutcome: 'Play 10 songs from memory',
    successMetrics: ['Play 10 songs', 'Perform for friends/family', 'Enjoy playing music'],
    difficulty: 'medium',
    tags: ['music', 'creativity', 'skills'],
    isBuiltIn: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // FINANCE GOALS (2 templates)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'g-emergency-fund',
    title: 'Build $10,000 Emergency Fund',
    description: 'Save 3-6 months of expenses for financial security',
    category: 'finance',
    icon: '💰',
    timeframe: '12 months',
    timeframeDays: 365,
    suggestedHabits: ['h-track-expenses', 'h-no-impulse-buying'],
    suggestedMilestones: [
      { title: 'Foundation', description: 'Set up systems', weekNumber: 4, objectives: ['Open high-yield savings', 'Set up automatic transfers', 'Track current spending'] },
      { title: '$2,500 Saved', description: 'First quarter', weekNumber: 13, objectives: ['Save $2,500', 'Find one expense to cut', 'Establish saving habit'] },
      { title: 'Halfway There', description: '$5,000 saved', weekNumber: 26, objectives: ['Reach $5,000', 'Increase savings rate', 'Resist lifestyle inflation'] },
      { title: 'Goal Complete', description: '$10,000 saved', weekNumber: 52, objectives: ['Hit $10,000', 'Maintain for emergencies only', 'Plan next financial goal'] },
    ],
    targetOutcome: 'Have $10,000 in easily accessible savings',
    successMetrics: ['$10,000 saved', 'No dipping into fund', 'Financial peace of mind'],
    difficulty: 'medium',
    tags: ['saving', 'finance', 'security'],
    popular: true,
    isBuiltIn: true,
  },
  {
    id: 'g-debt-free',
    title: 'Become Debt Free',
    description: 'Pay off all consumer debt (credit cards, car loans, etc.)',
    category: 'finance',
    icon: '🆓',
    timeframe: '24 months',
    timeframeDays: 730,
    suggestedHabits: ['h-track-expenses', 'h-no-impulse-buying'],
    targetOutcome: 'Zero consumer debt balance',
    successMetrics: ['Pay off all consumer debt', 'Build healthy spending habits', 'Financial freedom'],
    difficulty: 'hard',
    tags: ['debt', 'finance', 'freedom'],
    isBuiltIn: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════════
  // MINDFULNESS & WELLNESS GOALS (2 templates)
  // ═══════════════════════════════════════════════════════════════════════════════
  {
    id: 'g-meditation-365',
    title: 'Meditate for 365 Days',
    description: 'Build an unbreakable daily meditation practice',
    category: 'mindfulness',
    icon: '🧘',
    timeframe: '12 months',
    timeframeDays: 365,
    suggestedHabits: ['h-meditation', 'h-gratitude-journal', 'h-evening-reflection'],
    suggestedMilestones: [
      { title: 'First Month', description: 'Establish the habit', weekNumber: 4, objectives: ['30-day streak', 'Find best time to meditate', 'Explore different styles'] },
      { title: '100 Days', description: 'Centennial milestone', weekNumber: 14, objectives: ['100-day streak', 'Increase to 15 minutes', 'Notice mental changes'] },
      { title: 'Halfway', description: '6 months of daily meditation', weekNumber: 26, objectives: ['180-day streak', 'Try silent meditation', 'Handle missed days gracefully'] },
      { title: 'One Year', description: '365 days complete!', weekNumber: 52, objectives: ['365-day streak', 'Integrate mindfulness throughout day', 'Share practice with others'] },
    ],
    targetOutcome: 'Meditate every day for a full year',
    successMetrics: ['365-day streak', 'Improved emotional regulation', 'Reduced stress levels'],
    difficulty: 'hard',
    tags: ['meditation', 'mindfulness', 'streak'],
    popular: true,
    isBuiltIn: true,
  },
  {
    id: 'g-sleep-quality',
    title: 'Optimize Sleep Quality',
    description: 'Transform your sleep for better health and energy',
    category: 'health',
    icon: '😴',
    timeframe: '2 months',
    timeframeDays: 60,
    suggestedHabits: ['h-sleep-early', 'h-no-screens-bed', 'h-sleep-routine'],
    targetOutcome: 'Wake up feeling refreshed every morning',
    successMetrics: ['7-8 hours of sleep nightly', 'Fall asleep within 15 minutes', 'No daytime fatigue'],
    difficulty: 'medium',
    tags: ['sleep', 'health', 'energy'],
    isBuiltIn: true,
  },
];

// ─────────────────────────────────────────────────────────────────────────────────
// TEMPLATE BUNDLES (Pre-made combinations)
// ─────────────────────────────────────────────────────────────────────────────────

export const TEMPLATE_BUNDLES: TemplateBundle[] = [
  {
    id: 'bundle-morning-routine',
    name: 'Ultimate Morning Routine',
    description: 'Start every day with energy and purpose',
    icon: '🌅',
    habitTemplates: HABIT_TEMPLATES.filter(h => 
      ['h-exercise-morning', 'h-meditation', 'h-water-intake', 'h-reading', 'h-gratitude-journal'].includes(h.id)
    ),
    goalTemplates: [],
    tags: ['morning', 'routine', 'productivity'],
    author: 'Ascendify Team',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'bundle-productivity-master',
    name: 'Productivity Master',
    description: 'Maximize your daily output and achieve more',
    icon: '🚀',
    habitTemplates: HABIT_TEMPLATES.filter(h => 
      ['h-deep-work', 'h-plan-tomorrow', 'h-pomodoro-sessions', 'h-inbox-zero', 'h-no-social-media-morning'].includes(h.id)
    ),
    goalTemplates: GOAL_TEMPLATES.filter(g => g.id === 'g-get-promoted'),
    tags: ['productivity', 'focus', 'career'],
    author: 'Ascendify Team',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'bundle-fitness-starter',
    name: 'Fitness Starter Pack',
    description: 'Begin your fitness journey with sustainable habits',
    icon: '💪',
    habitTemplates: HABIT_TEMPLATES.filter(h => 
      ['h-exercise-morning', 'h-10k-steps', 'h-stretching', 'h-water-intake', 'h-no-junk-food'].includes(h.id)
    ),
    goalTemplates: GOAL_TEMPLATES.filter(g => g.id === 'g-run-5k'),
    tags: ['fitness', 'beginner', 'health'],
    author: 'Ascendify Team',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'bundle-mindful-life',
    name: 'Mindful Living',
    description: 'Reduce stress and find inner peace',
    icon: '🧘',
    habitTemplates: HABIT_TEMPLATES.filter(h => 
      ['h-meditation', 'h-gratitude-journal', 'h-digital-detox', 'h-nature-time', 'h-evening-reflection'].includes(h.id)
    ),
    goalTemplates: GOAL_TEMPLATES.filter(g => g.id === 'g-meditation-365'),
    tags: ['mindfulness', 'wellness', 'peace'],
    author: 'Ascendify Team',
    createdAt: new Date().toISOString(),
  },
  {
    id: 'bundle-knowledge-seeker',
    name: 'Knowledge Seeker',
    description: 'Never stop learning and growing',
    icon: '📚',
    habitTemplates: HABIT_TEMPLATES.filter(h => 
      ['h-reading', 'h-language-practice', 'h-online-course', 'h-learn-vocabulary', 'h-teach-something'].includes(h.id)
    ),
    goalTemplates: GOAL_TEMPLATES.filter(g => ['g-read-50-books', 'g-learn-language'].includes(g.id)),
    tags: ['learning', 'reading', 'growth'],
    author: 'Ascendify Team',
    createdAt: new Date().toISOString(),
  },
];

// ─────────────────────────────────────────────────────────────────────────────────
// CATEGORY METADATA
// ─────────────────────────────────────────────────────────────────────────────────

export const TEMPLATE_CATEGORIES: Record<TemplateCategory, { label: string; icon: string; color: string }> = {
  health: { label: 'Health', icon: '❤️', color: '#EF4444' },
  fitness: { label: 'Fitness', icon: '💪', color: '#10B981' },
  productivity: { label: 'Productivity', icon: '🎯', color: '#F59E0B' },
  learning: { label: 'Learning', icon: '📚', color: '#8B5CF6' },
  mindfulness: { label: 'Mindfulness', icon: '🧘', color: '#6366F1' },
  social: { label: 'Social', icon: '👥', color: '#EC4899' },
  finance: { label: 'Finance', icon: '💰', color: '#22C55E' },
  creative: { label: 'Creative', icon: '🎨', color: '#F43F5E' },
  career: { label: 'Career', icon: '💼', color: '#3B82F6' },
  sleep: { label: 'Sleep', icon: '😴', color: '#7C3AED' },
  nutrition: { label: 'Nutrition', icon: '🥗', color: '#14B8A6' },
  relationships: { label: 'Relationships', icon: '💝', color: '#EC4899' },
  'personal-growth': { label: 'Personal Growth', icon: '🌱', color: '#22C55E' },
};

// ─────────────────────────────────────────────────────────────────────────────────
// HELPER FUNCTIONS
// ─────────────────────────────────────────────────────────────────────────────────

export function getHabitTemplateById(id: string): HabitTemplate | undefined {
  return HABIT_TEMPLATES.find(h => h.id === id);
}

export function getGoalTemplateById(id: string): GoalTemplate | undefined {
  return GOAL_TEMPLATES.find(g => g.id === id);
}

export function getTemplatesByCategory(category: TemplateCategory): { habits: HabitTemplate[]; goals: GoalTemplate[] } {
  return {
    habits: HABIT_TEMPLATES.filter(h => h.category === category),
    goals: GOAL_TEMPLATES.filter(g => g.category === category),
  };
}

export function getPopularTemplates(): { habits: HabitTemplate[]; goals: GoalTemplate[] } {
  return {
    habits: HABIT_TEMPLATES.filter(h => h.popular),
    goals: GOAL_TEMPLATES.filter(g => g.popular),
  };
}

export function searchTemplates(query: string): { habits: HabitTemplate[]; goals: GoalTemplate[] } {
  const lowerQuery = query.toLowerCase();
  return {
    habits: HABIT_TEMPLATES.filter(h => 
      h.name.toLowerCase().includes(lowerQuery) ||
      h.description.toLowerCase().includes(lowerQuery) ||
      h.tags?.some(t => t.toLowerCase().includes(lowerQuery))
    ),
    goals: GOAL_TEMPLATES.filter(g =>
      g.title.toLowerCase().includes(lowerQuery) ||
      g.description.toLowerCase().includes(lowerQuery) ||
      g.tags?.some(t => t.toLowerCase().includes(lowerQuery))
    ),
  };
}
